USE [PhoenixMobile]
GO

/****** Object:  Table [dbo].[TBLMOBILEUSERSIGNUP]    Script Date: 19-04-2021 12:42:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBLMOBILEUSERSIGNUP](
	[FLDUSERID] [uniqueidentifier] NULL,
	[FLDUSERNAME] [varchar](500) NULL,
	[FLDPASSWORD] [varchar](500) NULL,
	[FLDCREATEDDATE] [datetime] NULL,
	[FLDCREATEDBY] [int] NULL,
	[FLDMODIFIEDDATE] [datetime] NULL,
	[FLDMODIFIEDBY] [int] NULL,
	[FLDDTKEY] [uniqueidentifier] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBLMOBILEUSERSIGNUP] ADD  CONSTRAINT [DF_TBLMOBILEUSERSIGNUP_FLDUSERID]  DEFAULT (newsequentialid()) FOR [FLDUSERID]
GO

ALTER TABLE [dbo].[TBLMOBILEUSERSIGNUP] ADD  CONSTRAINT [DF_TBLMOBILEUSERSIGNUP_FLDDTKEY]  DEFAULT (newsequentialid()) FOR [FLDDTKEY]
GO

